<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class KategoriPerbuSeeder extends Seeder
{
    public function run()
    {
        // Kosongkan tabel categories terlebih dahulu (opsional)
        // Jika tidak ingin menghapus data lama, comment baris di bawah
        $this->db->table('categories')->emptyTable();

        $data = [
            [
                'name'        => 'BAHAN BANGUNAN DAN KONSTRUKSI',
                'description' => 'Barang Pakai Habis | Kode: 8.01.01.01.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'BAHAN KIMIA',
                'description' => 'Barang Pakai Habis | Kode: 8.01.01.02.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'BAHAN PELEDAK',
                'description' => 'Barang Pakai Habis | Kode: 8.01.01.03.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'BAHAN BAKAR DAN PELUMAS',
                'description' => 'Barang Pakai Habis | Kode: 8.01.01.04.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'BAHAN BAKU',
                'description' => 'Barang Pakai Habis | Kode: 8.01.01.05.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'BAHAN KIMIA NUKLIR',
                'description' => 'Barang Pakai Habis | Kode: 8.01.01.06.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'BARANG DALAM PROSES',
                'description' => 'Barang Pakai Habis | Kode: 8.01.01.07.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'BAHAN LAINNYA',
                'description' => 'Barang Pakai Habis | Kode: 8.01.01.99.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'SUKU CADANG ALAT ANGKUTAN',
                'description' => 'Barang Pakai Habis | Kode: 8.01.02.01.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'SUKU CADANG ALAT BESAR',
                'description' => 'Barang Pakai Habis | Kode: 8.01.02.02.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'SUKU CADANG ALAT KEDOKTERAN',
                'description' => 'Barang Pakai Habis | Kode: 8.01.02.03.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'SUKU CADANG ALAT LABORATORIUM',
                'description' => 'Barang Pakai Habis | Kode: 8.01.02.04.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'SUKU CADANG ALAT PEMANCAR',
                'description' => 'Barang Pakai Habis | Kode: 8.01.02.05.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'SUKU CADANG ALAT STUDIO DAN KOMUNIKASI',
                'description' => 'Barang Pakai Habis | Kode: 8.01.02.06.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'SUKU CADANG ALAT PERTANIAN',
                'description' => 'Barang Pakai Habis | Kode: 8.01.02.07.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'SUKU CADANG ALAT BENGKEL',
                'description' => 'Barang Pakai Habis | Kode: 8.01.02.08.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'SUKU CADANG LAINNYA',
                'description' => 'Barang Pakai Habis | Kode: 8.01.02.99.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'ALAT TULIS KANTOR',
                'description' => 'Barang Pakai Habis | Kode: 8.01.03.01.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'KERTAS DAN COVER',
                'description' => 'Barang Pakai Habis | Kode: 8.01.03.02.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'BAHAN CETAK',
                'description' => 'Barang Pakai Habis | Kode: 8.01.03.03.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'BAHAN KOMPUTER',
                'description' => 'Barang Pakai Habis | Kode: 8.01.03.04.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'PERABOT KANTOR',
                'description' => 'Barang Pakai Habis | Kode: 8.01.03.05.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'ALAT LISTRIK',
                'description' => 'Barang Pakai Habis | Kode: 8.01.03.06.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'PERLENGKAPAN DINAS',
                'description' => 'Barang Pakai Habis | Kode: 8.01.03.07.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'KAPORLAP DAN PERLENGKAPAN SATWA',
                'description' => 'Barang Pakai Habis | Kode: 8.01.03.08.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'ALAT/BAHAN UNTUK KEGIATAN KANTOR LAINNYA',
                'description' => 'Barang Pakai Habis | Kode: 8.01.03.09.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'OBAT',
                'description' => 'Barang Pakai Habis | Kode: 8.01.04.01.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'PERSEDIAAN UNTUK DIJUAL/DISERAHKAN KEPADA MASYARAKAT',
                'description' => 'Barang Pakai Habis | Kode: 8.01.05.01.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'PERSEDIAAN UNTUK TUJUAN STRATEGIS/BERJAGA-JAGA',
                'description' => 'Barang Pakai Habis | Kode: 8.01.06.01.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'NATURA',
                'description' => 'Barang Pakai Habis | Kode: 8.01.07.01.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'PAKAN',
                'description' => 'Barang Pakai Habis | Kode: 8.01.07.02.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'NATURA DAN PAKAN LAINNYA',
                'description' => 'Barang Pakai Habis | Kode: 8.01.07.99.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'PERSEDIAAN PENELITIAN BIOLOGI',
                'description' => 'Barang Pakai Habis | Kode: 8.01.08.01.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'KOMPONEN JEMBATAN BAJA',
                'description' => 'Barang Tak Habis Pakai | Kode: 8.02.01.01.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'KOMPONEN JEMBATAN PRATEKAN',
                'description' => 'Barang Tak Habis Pakai | Kode: 8.02.01.02.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'KOMPONEN PERALATAN',
                'description' => 'Barang Tak Habis Pakai | Kode: 8.02.01.03.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'KOMPONEN RAMBU-RAMBU',
                'description' => 'Barang Tak Habis Pakai | Kode: 8.02.01.04.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'ATTACHMENT',
                'description' => 'Barang Tak Habis Pakai | Kode: 8.02.01.05.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'KOMPONEN LAINNYA',
                'description' => 'Barang Tak Habis Pakai | Kode: 8.02.01.99.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'PIPA AIR BESI TUANG (DCI)',
                'description' => 'Barang Tak Habis Pakai | Kode: 8.02.02.01.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'PIPA ASBES SEMEN (ACP)',
                'description' => 'Barang Tak Habis Pakai | Kode: 8.02.02.02.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'PIPA BAJA',
                'description' => 'Barang Tak Habis Pakai | Kode: 8.02.02.03.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'PIPA BETON PRATEKAN',
                'description' => 'Barang Tak Habis Pakai | Kode: 8.02.02.04.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'PIPA FIBER GLASS',
                'description' => 'Barang Tak Habis Pakai | Kode: 8.02.02.05.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'PIPA PLASTIK PVC (UPVC)',
                'description' => 'Barang Tak Habis Pakai | Kode: 8.02.02.06.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'P I P A LAINNYA',
                'description' => 'Barang Tak Habis Pakai | Kode: 8.02.02.99.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'RAMBU-RAMBU',
                'description' => 'Barang Tak Habis Pakai | Kode: 8.02.03.01.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'KOMPONEN BEKAS',
                'description' => 'Barang Bekas Dipakai | Kode: 8.03.01.01.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'PIPA BEKAS',
                'description' => 'Barang Bekas Dipakai | Kode: 8.03.01.02.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
            [
                'name'        => 'KOMPONEN BEKAS DAN PIPA BEKAS LAINNYA',
                'description' => 'Barang Bekas Dipakai | Kode: 8.03.01.99.000',
                'is_active'   => 1,
                'created_at'  => date('Y-m-d H:i:s'),
                'updated_at'  => date('Y-m-d H:i:s'),
            ],
        ];

        // Using Query Builder
        $this->db->table('categories')->insertBatch($data);
    }
}
